import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import fs from 'fs';
import path from 'path';
import MarkdownRenderer from '@/components/MarkdownRenderer';
import SchemeDetails from './SchemeDetails';

interface SpeciesPageProps {
  params: Promise<{ genus: string; species: string }>;
}

interface IndexEntry {
  species: string;
  preferred_scheme: string | null;
  schemes: { scheme: string; manifest_url: string }[];
}

function loadIndex(p: string): { species: IndexEntry[] } | null {
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// Combine the canonical /api/v2/index.json with /api/v2/external/index.json
// so the scheme switcher on the species page sees both QualiBact-published
// schemes AND third-party schemes (enterobase-v2.3 etc.).
function loadMergedIndex(): { species: IndexEntry[] } | null {
  const qb = loadIndex(path.join(process.cwd(), 'public', 'api', 'v2', 'index.json'));
  const ext = loadIndex(path.join(process.cwd(), 'public', 'api', 'v2', 'external', 'index.json'));
  if (!qb && !ext) return null;
  const merged = new Map<string, IndexEntry>();
  for (const e of qb?.species ?? []) {
    merged.set(e.species, { ...e, schemes: [...e.schemes] });
  }
  for (const e of ext?.species ?? []) {
    const existing = merged.get(e.species);
    if (existing) {
      const seen = new Set(existing.schemes.map((s) => s.scheme));
      for (const s of e.schemes) if (!seen.has(s.scheme)) existing.schemes.push(s);
    } else {
      merged.set(e.species, { ...e, preferred_scheme: e.preferred_scheme ?? null, schemes: [...e.schemes] });
    }
  }
  return { species: [...merged.values()] };
}

function loadManifest(species: string, version: string): { counts: { genome_count: number; refseq_count: number } } | null {
  const p = path.join(process.cwd(), 'public', 'static', 'species', species, version, 'manifest.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
}

export async function generateStaticParams() {
  const idx = loadMergedIndex();
  if (!idx) return [];
  return idx.species
    .map(({ species }) => ({
      genus: species.split('_')[0],
      species,
    }))
    .filter((p) => !!p.genus);
}

export async function generateMetadata({ params }: SpeciesPageProps): Promise<Metadata> {
  const { species } = await params;
  const prettyName = species.replace(/_/g, ' ');
  return {
    title: `${prettyName} QC`,
    description: `Quality control thresholds and genome assembly metrics for ${prettyName}.`,
  };
}

export default async function SpeciesPage({ params }: SpeciesPageProps) {
  const { genus, species } = await params;
  const idx = loadMergedIndex();
  if (!idx) notFound();

  const entry = idx.species.find((s) => s.species === species);
  if (!entry) notFound();

  const allSchemes = entry.schemes.map((s) => s.scheme);
  const preferredVersion = entry.preferred_scheme ?? allSchemes[0];
  if (!preferredVersion) notFound();

  // Verify the manifest actually exists for the preferred scheme.
  const manifest = loadManifest(species, preferredVersion);
  if (!manifest) notFound();

  // Optional MDX content at content/{Species}/index.mdx — only used when
  // hand-authored, not when auto-generated by qualibact-pack.
  const contentPath = path.join(process.cwd(), 'content', species, 'index.mdx');
  let speciesContent = '# ' + species.replace(/_/g, ' ');
  let useContent = false;
  const qcMarkers = [
    'Download metrics CSV',
    'Genome_Size_refseq_histogram_kde.png',
    'RefSeq distributions',
    'Download high quality genomes list',
    'high_quality_genomes',
    'filtered_out_genomes',
    'RefSeq genomes',
    '## Version History',
    '## Plots and Visualizations',
    'Preferred QC scheme',
  ];
  const looksLikeQCGenerated = (maybe: string) => qcMarkers.some((k) => maybe.includes(k));
  const isGeneratedContent = (maybe: string) =>
    maybe.includes('generated_by: qualibact-pack') ||
    maybe.includes('generated_by: qualibact-to-nextjs');
  if (fs.existsSync(contentPath)) {
    try {
      const maybe = fs.readFileSync(contentPath, 'utf8');
      if (isGeneratedContent(maybe) && !looksLikeQCGenerated(maybe)) {
        useContent = true;
        speciesContent = maybe;
      }
    } catch {
      useContent = false;
    }
  }

  return (
    <div className="py-8">
      <div className="space-y-8">
        <header className="space-y-4">
          <h1 className="text-3xl font-bold font-header">
            <em>{species.replace(/_/g, ' ')}</em> QC Overview
          </h1>
        </header>

        {useContent && (
          <div className="card p-6">
            <MarkdownRenderer content={speciesContent} />
          </div>
        )}

        <h2 className="text-2xl font-header font-semibold text-neutral-800 dark:text-neutral-200">
          Preferred scheme: <strong>{preferredVersion}</strong>
        </h2>

        <SchemeDetails species={species} version={preferredVersion} />

        {allSchemes.length > 0 && (
          <div className="card p-6 space-y-4">
            <h3 className="text-xl font-semibold font-header text-neutral-800 dark:text-neutral-200">
              All QC schemes for this species
            </h3>
            <div className="flex flex-wrap gap-3">
              {allSchemes.map((version) => (
                <a
                  key={version}
                  href={`/${genus}/${species}/${version}`}
                  className={`inline-flex items-center px-4 py-2 rounded-full border ${version === preferredVersion ? 'border-brand-600 bg-brand-50 dark:bg-brand-900' : 'border-brand-500'} text-brand-600 dark:text-brand-300 hover:bg-brand-50 dark:hover:bg-brand-900`}
                >
                  {version === preferredVersion ? `${version} (preferred)` : version}
                </a>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
